### PR TITLE
Update cs.json

### PR DESCRIPTION
**Pull request by KarelZavicak**
Strings reordered to match en.json for easier future diffs (former cs.json was re-ordered alphabetically)
Added missing translation strings

### CODE REVIEW

**Comment by sdenec** [comment]
Thanks for your work but bit of a bad timing ... I'm currently in the process of rewriting the settings menu into a custom menu and changed a few string names and added a bunch more. Because of this your file actually can't be merged. I'd like to ask you to wait until I push the update and review your file. I'm very sorry for the additional work :(

**Comment by KarelZavicak** [comment]
Hi,

I don't have any problems with English, but some members of my group do, so
I would have to translate it anyways and then keep it locally. Once you
push your update, I'll translate it and create new pull request, so others
may use it. Czech DnD community is quite growing...

Regards,
KZ

**Comment by KarelZavicak** [comment]
> Thanks for your work but bit of a bad timing ... I'm currently in the process of rewriting the settings menu into a custom menu and changed a few string names and added a bunch more. Because of this your file actually can't be merged. I'd like to ask you to wait until I push the update and review your file. I'm very sorry for the additional work :(

Seems translation file was reverted to the one from January. Reason?

**Comment by sdenec** [comment]
Hi. I didn't merged the last request and used the latest file available at that point in the last update. That file should have all previously available strings renamed to the new string names. And if I tried to add all the new ones. Though I might have missed a few ... You are welcome to open a new merge request and I'm happy to integrate the file!

**Pull request closed without merging**
